name: Build UBI Image

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
#  IMAGE_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - uses: docker/metadata-action@v5
#        id: meta
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#          tags: |
#            type=ref,event=branch
#            type=ref,event=pr
#            type=semver,pattern={{version}}

      - run: |
          COMPONENT="${GITHUB_REF_NAME%%-*}"
          VERSION="${GITHUB_REF_NAME#*-}"
          echo "COMPONENT=$COMPONENT" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ env.COMPONENT }}/Dockerfile
          push: true
#          tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.COMPONENT }}-ubi:${{ env.VERSION }}
#          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/ubi-images:${{ env.VERSION }}
#          labels: ${{ steps.meta.outputs.labels }}
#          build-args: |
#            VERSION=${{ steps.meta.outputs.version }}
